/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Ignore;
import org.junit.Test;

public class BowlingGameTest {
    @Test
    @Ignore
    public void gutterGame() {
    }

    @Test
    @Ignore
    public void allOnes() {
    }

    @Test
    @Ignore
    public void oneSpare() {
    }

    @Test
    @Ignore
    public void oneStrike() {
    }

    @Test
    @Ignore
    public void perfectGame() {
    }
}
